### ISSUE TITLE
Tutorial page has the wrong code on Page.js

### ISSUE THREAD

**Issue by aaspinwall** [storyblok/nextjs-multilanguage-website#12]
I was following along the [tutorial](https://www.storyblok.com/tp/next-js-react-guide#connecting-storyblok-with-next-js) and kept getting an error. Then realized the Page.js code was the same as Grid.js

I checked the repo and found the right code.

<img width="902" alt="Screen Shot 2020-11-02 at 9 49 01 AM" src="https://user-images.githubusercontent.com/17233773/97881679-b1769700-1cf0-11eb-9aa6-0eb527b82227.png">

It should have this instead:

```
import DynamicComponent from "./DynamicComponent";
import SbEditable from "storyblok-react";

const Page = ({ content }) => (
  <SbEditable content={content}>
    <main>
      {content.body.map((blok) => (
        <DynamicComponent blok={blok} key={blok._uid} />
      ))}
    </main>
  </SbEditable>
);

export default Page;
```

**Comment by DominikAngerer** [comment]
Hey @aaspinwall! 
Thanks for catching that and letting us know :)
I've just updated it!
