### ISSUE TITLE
Updates to tutorial

### ISSUE THREAD

**Issue by lilybarrett** [storyblok/nextjs-multilanguage-website#2]
Hello! Overall, I'm really enjoying Storyblok -- the docs are mostly great, and so was this tutorial -- but I'd love to help make updates to this tutorial (fixing links, typos, and using updated NextJS concepts such as the use of an `_app.js`). What's the best way to contribute to the tutorial itself (in addition to its accompanying code)?

**Comment by DominikAngerer** [comment]
Hey @lilybarrett! Glad you like Storyblok so far. I'll transfer this repository to our @storyblok org. Let me know your mail -> da@storyblok.com, would love to huck you up with a Storyblok account and check for the possibilities on how to update the tutorial. Also I guess we have some Storyblok Merch ready for you! ;)

**Comment by DominikAngerer** [comment]
Transfered to: https://github.com/storyblok/nextjs-multilanguage-website/ :)

**Comment by lilybarrett** [comment]
@DominikAngerer Thanks so much! I already have a Storyblok account and have loved using the system so far (with React and Next.js). Looking forward to helping to update the docs/tutorials.

**Comment by lilybarrett** [comment]
By the way: Is there a repo for the tutorial itself? I can't seem to find it.

**Comment by DominikAngerer** [comment]
I'll invite you to a private git repo for the tutorial! :)

**Comment by lilybarrett** [comment]
Perfect! Thanks.
