### ISSUE TITLE
Tutorial CSS

### ISSUE THREAD

**Issue by Datagrdn** [storyblok/nextjs-multilanguage-website#20]
Hey there!

Following along with the tutorial and something's up with the CSS. This is what I see after initially importing Layout into index.js

![Screen Shot 2021-02-28 at 6 35 50 PM](https://user-images.githubusercontent.com/32917271/109445139-ca1f6100-79f3-11eb-9830-30ac77a46ee3.png)

I even copy and pasted the examples but still getting this, any idea what's up?

Thanks so much!

**Comment by Datagrdn** [comment]
Ah ok!

Here is the solution:

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by lisilinhart** [comment]
Should be working with the update
